(function() {
  angular.module('genders', [])
  .service('genders', function() {
    return [
      "Agender",
      "Ambigender",
      "Androgyne",
      "Androgynous",
      "Bigender",
      "Boi",
      "Boy",
      "Butch",
      "Cis Female",
      "Cis Feminine",
      "Cis Male",
      "Cis Man",
      "Cis Masculine",
      "Cis Woman",
      "Demiboy",
      "Demigirl",
      "Demiguy",
      "Demiwoman",
      "Female",
      "Femboy",
      "Feminine",
      "Femme",
      "Genderqueer",
      "Genderweird",
      "Gender Fluid",
      "Girl",
      "Gender Neutral"
      "Intergender",
      "Intersex",
      "Male",
      "Man",
      "Masculine",
      "Neutrois",
      "Nonbinary",
      "Other",
      "Pangender",
      "Third Gender",
      "Trans Female",
      "Trans Feminine",
      "Trans Male",
      "Trans Man",
      "Trans Masculine",
      "Trans Woman",
      "Woman"
    ];
  });
})();